### ISSUE TITLE
[UI] Implement toast notifications

### ISSUE THREAD

**Issue by vitaliy-bobrov** [vitaliy-bobrov/js-rocks#16]

**Comment by vitaliy-bobrov** [comment]
Show notification toast after preset: update, create, delete

**Comment by MIKOLAJW197** [comment]
@vitaliy-bobrov  You thinking about implementing toast notifications from scratch? Or maybe using for example: **ngx-toastr** or **angular-notifier** ?
I'd like to know more because I am thinking about grabing this issue.

**Comment by vitaliy-bobrov** [comment]
Hi @MIKOLAJW197, first of all thanks for your interest in contribution! and sorry for a delayed reply.

I'm using Angular Material in the project and snackbar component would do the job for the task. You can find the docs here: https://material.angular.io/components/snack-bar/overview.

Let me know if you have any questions.

**Comment by MIKOLAJW197** [comment]
@vitaliy-bobrov First of all thanks for anwser!
Secondly thanks for showing this **snackbar**, because I didn't know that component. 

As I said I will handle this issue, and open PR soon!
