### ISSUE TITLE
[a11y] Add codelyzer a11y checks

### ISSUE THREAD

**Issue by vitaliy-bobrov** [vitaliy-bobrov/js-rocks#27]
Add a11y checks based on https://web.dev/accessible-angular-with-codelyzer/

**Comment by sanketmaru** [comment]
I can take up this issue and happy to contribute.

**Comment by vitaliy-bobrov** [comment]
Assigned to you. Thanks for your interest ;)

**Comment by vitaliy-bobrov** [comment]
Fixed by #28
