### ISSUE TITLE
Create Tremolo - JTR-2

### ISSUE THREAD

**Issue by adamfr33man** [vitaliy-bobrov/js-rocks#6]
Loving the project, I wanted to have a go at making a Tremolo and after that will hopefully be able to help with more effects. I'll submit a PR when I've got it working

**Comment by vitaliy-bobrov** [comment]
@adamfr33man - Glad to hear about your interest in the project! I believe you have almost all building blocks to implement it. The only thing left (if you want to implement the same effect as TR-2) is a oscillator wave transformation from triangle to square. Let me know if you need any help. Waiting for the PR. Thanks a lot!

**Comment by adamfr33man** [comment]
Yeah that is the one thing that seemed the most complicated part - If it were a switch from triangle to square then that seems pretty simple, but was thinking about taking a saw wave and distorting it to a square wave as the value increases ... but I may have to see if there's any info on how they actually do it in existing pedals.

So far I have a basic pedal with adjustable rate (and soon to have depth). As soon as I have suitable ranges on the rate I'll send you a link to my branch ... by that time one or both of us may have good ideas on how to do the wave shape.
